services:
  - type: web
    name: youtube-downloader-api
    runtime: node
    rootDir: backend
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: ALLOWED_ORIGINS
        value: https://luvpatel.net,http://localhost:3000,http://localhost:3002,http://192.168.68.101:3002
    plan: free
