services:
  - type: web
    name: youtube-downloader-api
    runtime: node
    region: ohio
    rootDir: backend
    buildCommand: pip install yt-dlp && npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3001
      - key: ALLOWED_ORIGINS
        value: https://luvportoflio.netlify.app,https://luvpatel.net,http://localhost:3000,http://localhost:3001,http://localhost:3002
    plan: free
